### ISSUE TITLE
Fairs experience on ipad needs to re route to native artwork views

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#107]
Tapping on a work in a fair leads to the web view and can not be scrolled.

**Comment by katarinabatina** [comment]
Specifically a problem coming from browse view, when navigating from "for you" section within a fair the native artwork view shows up

**Comment by ashfurrow** [comment]
Cool.

**Comment by ashfurrow** [comment]
I mean, the bug is not _cool_, but I'll take a look.

**Comment by katarinabatina** [comment]
@ashfurrow No teasing haha!!! Orta just gave me the "assign issues to people" job and I asked for a profile of preferences for each of you. You were noted to be "interested in fairs" 

:+1:

**Comment by 1aurabrown** [comment]
i'm going to take a look at this since i'm currently going through ipad issues

**Comment by 1aurabrown** [comment]
this was fixed, i think this bug was caused by the change to `www`, which initially wasn't reflected in eigen but now is fixed. closing.

**Comment by katarinabatina** [comment]
Just checked this it's still a problem and definitely a launch blocker

**Comment by 1aurabrown** [comment]
Ok, I couldn't repro but maybe i got the dlow wrong. I went to a fair, which was
a web view, and then a work, which was native. Can you show me irl what you did
to trigger this?

On Fri, Apr 10, 2015 at 20:08, artsy/eigen
<reply@reply.github.com>
wrote:Just checked this it's still a problem and definitely a launch blocker

—
Reply to this email directly or view it on GitHub
[https://github.com/artsy/eigen/issues/107#issuecomment-91725052] .[https://github.com/notifications/beacon/ADBlTn_aME3Tevedpp-wI6dMSdwNyk6Iks5n-F16gaJpZM4Dc6Ku.gif]

**Comment by katarinabatina** [comment]
1. Go to art fair overview, tap Browse all exhibitors entry point, leads to non-native artwork view
2. Go to art fair overview, tap a gene/section entry point, scroll down the page, select work, leads to non-native view

**Comment by 1aurabrown** [comment]
force issue - https://github.com/artsy/force/issues/2596

**Comment by 1aurabrown** [comment]
should be closed by https://github.com/artsy/force/pull/2597
