### ISSUE TITLE
change app category in itunes connect for next release

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1233]
change 1. Lifestyle 2. Education to 1. Shopping 2. Lifestyle

![image](https://cloud.githubusercontent.com/assets/6482926/13539971/b56262d6-e221-11e5-87e2-e819486a71f8.png)

**Comment by alloy** [comment]
Done for 2.4.0 which is now in review.

**Comment by katarinabatina** [comment]
Oh I was hoping to submit new copy for the store as well, is there a reason we're shipping 2.4 now? 

Sent with thumbs,
Katarina Batina 
Product Designer
Artsy.net

**Comment by orta** [comment]
That can still happen, I think

-- 
     [ ·/ ]  Orta Therox
w/  Artsy
CocoaPods /  CocoaDocs / GIFs
@orta  /  orta.io

On 10 March 2016 at 20:41:09, Katarina Batina (notifications@github.com) wrote:

Oh I was hoping to submit new copy for the store as well, is there a reason we're shipping 2.4 now?

Sent with thumbs,
Katarina Batina
Product Designer
Artsy.net

**Comment by alloy** [comment]
> Oh I was hoping to submit new copy for the store as well, is there a reason we're shipping 2.4 now?

Yeah that’s still possible.

The reason to release now was only because of the bug that removed all on-boarding on the initial launch and we’re losing account sign-ups. But if you want we can imo wait a few more days and maybe also get the new works for you view in?
